stages:
- name: step1
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: api-admin
      registry: sandbox-images
- name: clear
  steps:
  - runScriptConfig:
      image: php:latest
      shellScript: docker rmi $(docker images -q)
timeout: 60
notification: {}
