stages:
- name: step1
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: api-admin
      pushRemote: true
      registry: sandbox-images
timeout: 60
notification: {}
